language: python
python:
- '3.6'
install:
- pip install requests invoke
cache: pip
script:
    - true
git:
  depth: 3
deploy:
  provider: script
  script: bash build.sh
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$
