os: linux
arch:
  - arm64
language: python
python:
  - "3.6"
install:
  - pip install progressbar2 requests invoke boto3 aws-requests-auth jsonschema python-xlib
script:
  - echo "hello"
  - invoke poll-ci-build
